### ISSUE TITLE
Image.ANTIALIAS python problem [Solved]

### ISSUE THREAD

**Issue by mgalvi** [huntfx/MouseTracks#63]
For anyone with problems generating images I just changed Image.ANTIALIAS to Image.LANCZOS in all instances inside moutracks/images/main.py.

I'm just creating the issue to announce this. 

**Take a look at this awesome result**

![180 Clicks (LMB) - Jet](https://github.com/huntfx/MouseTracks/assets/140488982/f439f43f-7c77-43d9-97dc-9cd7458fbd12)

**Comment by huntfx** [comment]
Cool render and thanks for finding a workaround :)
The whole codebase kinda stopped being supported after Python 3.7 (I see a few other errors attempting to run for 3.10) - at some point I need to do a complete rewrite and bring everything up to date.

Just for the sake of comparison if you decide to keep the script running, here's mine after a few years:

![16755499 Clicks (Combined) - Jet](https://github.com/huntfx/MouseTracks/assets/10235666/f0ffd8b4-d7bc-4115-978f-e9d92c9e03a2)

**Comment by huntfx** [comment]
Thanks, and yeah I'm sadly aware launching it for the first time isn't easy, would have been happy to help out.

My rewrite plan is to build everything from the ground up with GUI support being a big focus so that anyone can use it. I likely won't have any free time super soon, but you've motivated me a bit to start up again at some point lol.

**Comment by huntfx** [comment]
One year later and I've _finally_ made a start on it. It's got a live render preview and and is much faster, so should be a ton nicer to use once it's ready.

I don't know why I didn't push out a fix before, but I've done it now haha.
